### ISSUE TITLE
How to build vdPoisMex.c on Windows

### ISSUE THREAD

**Issue by ShannonZ** [jtamir/t2shuffling-support#1]
Cannot build vdPoisMex.c using mex  vdPoisMex.c

**Comment by jtamir** [comment]
What error do you get when you try to compile? I don't have a Windows machine to test. On a Mac, I get this when I run it:
```
mex vdPoisMex.c
Building with 'Xcode with Clang'.
MEX completed successfully.
```
My Matlab environment is set up to build with Mac's compiler. I expect for Windows the compiler will be different.

**Comment by ShannonZ** [comment]
A lot of syntax errors detected by cl.exe.

Building with 'Microsoft Visual C++ 2015 (C)'.
Error using mex
vdPoisMex.c

F:\MATLAB\phase_cycling-master\utils\vdPoisMex.c(25): error C2143: syntax error: missing“;”(before“*”)
F:\MATLAB\phase_cycling-master\utils\vdPoisMex.c(25): error C2059: syntax error:“*”
F:\MATLAB\phase_cycling-master\utils\vdPoisMex.c(26): error C2059: syntax error:“}”
F:\MATLAB\phase_cycling-master\utils\vdPoisMex.c(34): error C2143: syntax error:  missing“;”(before“*”)
F:\MATLAB\phase_cycling-master\utils\vdPoisMex.c(34): error C2059: syntax error:“*”
... 
CTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::Invo

**Comment by ShannonZ** [comment]
Are there any alternatives  to this c file?
 Or pure-Matlab version of it?  I don't care about the speed.

**Comment by jtamir** [comment]
Unfortunately I don't have a non-mex version, but you could try using any other variable density sampling pattern for now. There is also a poisson disc sampling pattern in BART (github.com/mrirecon/bart) that you could use in place of this.
If you want, I can generate the sampling patterns for you, if you tell me what settings you want.
Very sorry about that.

**Comment by ShannonZ** [comment]
I can run [the python implementation ](http://devmag.org.za/2009/05/03/poisson-disk-sampling/) to get a mask. I just confused that if the image matrices are the same, whether I can use the same mask for all samplings or not?

**Comment by jtamir** [comment]
You can use BART with the Linux subsystem for Windows. If you don't mind using Python then I recommend you use the implementation in Sigpy: https://sigpy.readthedocs.io/en/latest/generated/sigpy.mri.poisson.html#sigpy.mri.poisson
The usage would be something like this:
```python
mask = sigpy.mri.samp.poisson([ny, nz], Ry*Rz, calib = [cal_size, cal_size], crop_corner=cut_corners, seed=random_seed)
```
This also support variable density sampling.

Thanks

**Comment by ShannonZ** [comment]
SciPy is a great package! Thank you for this helpful info.

**Comment by ShannonZ** [comment]
@jtamir Sorry to disturb you. But I just wanna know if you could tell me some articles about how to solve the wavelet based regularization problem. 
I need some text to help understand the algorithm details about "SigPy for MRI Tutorial Part 3: Building an L1 Wavelet Reconstruction App". Please help~

**Comment by jtamir** [comment]
A good starting point is Miki Lustig's webpage on CS MRI: 
http://people.eecs.berkeley.edu/~mlustig/CS.html

It has links to two good papers to check out.

Cheers

**Comment by jtamir** [comment]
I made a T2 Shuffling demo using SigPy, here:
https://github.com/jtamir/t2sh-python/blob/master/T2%20Shuffling%20Sigpy%20Demo.ipynb

**Comment by ShannonZ** [comment]
Thanks very much! I've learned a lot from Miki Lustig's webpage.
